name: Release Docker Images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pescarte-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/pescarte-backend:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pescarte-frontend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/pescarte-frontend:${{ steps.get_version.outputs.VERSION }}